apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin-container
        image: phpmyadmin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: PMA_HOST
            value: "cip-mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: lb-phpmyadmin
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000
  selector:
    app: phpmyadmin