apiVersion: 1
datasources:
- name: influxdb
  type: influxdb
  orgId: 1
  url: http://cip-influxdb:8086
  database: telegraf
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: root
  basicAuthPassword: root